SELECT 
    J.JOB_NAME,
    MAX(H.START_TIME) AS LAST_START_TIME,
    MAX(H.END_TIME)   AS LAST_END_TIME,
    MAX(H.STATUS)     AS LAST_STATUS
FROM AL_HISTORY H
JOIN AL_LANGUAGES L ON H.LANG_ID = L.LANG_ID
JOIN AL_JOBINFO J ON H.JOB_ID = J.JOB_ID
GROUP BY J.JOB_NAME
ORDER BY LAST_START_TIME DESC;
